spring:
  application:
    name: form-based

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sec_form
    username: root
    password: admin1234!

  jpa:
    hibernate:
      ddl-auto: create


